version: "3"

services:
  authentication-server:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    environment:
      PORT: 50051
      ENV: development
    ports:
      - 50051:50051
    volumes:
      - .:/go/src/github.com/abyssparanoia/catharsis
    command: ash -c "realize start"
