// Code generated by MockGen. DO NOT EDIT.
// Source: ./sign_service.go

// Package mock_jwtauth is a generated GoMock package.
package mock_jwtauth

import (
	context "context"
	jwtauth "github.com/abyssparanoia/catharsis/pkg/jwtauth"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockJwtauthSign is a mock of JwtauthSign interface
type MockJwtauthSign struct {
	ctrl     *gomock.Controller
	recorder *MockJwtauthSignMockRecorder
}

// MockJwtauthSignMockRecorder is the mock recorder for MockJwtauthSign
type MockJwtauthSignMockRecorder struct {
	mock *MockJwtauthSign
}

// NewMockJwtauthSign creates a new mock instance
func NewMockJwtauthSign(ctrl *gomock.Controller) *MockJwtauthSign {
	mock := &MockJwtauthSign{ctrl: ctrl}
	mock.recorder = &MockJwtauthSignMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockJwtauthSign) EXPECT() *MockJwtauthSignMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method
func (m *MockJwtauthSign) GenerateToken(ctx context.Context, claims *jwtauth.Claims) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", ctx, claims)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateToken indicates an expected call of GenerateToken
func (mr *MockJwtauthSignMockRecorder) GenerateToken(ctx, claims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockJwtauthSign)(nil).GenerateToken), ctx, claims)
}
