// Code generated by MockGen. DO NOT EDIT.
// Source: ./verify_service.go

// Package mock_jwtauth is a generated GoMock package.
package mock_jwtauth

import (
	context "context"
	jwtauth "github.com/abyssparanoia/catharsis/pkg/jwtauth"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockJwtauthVerify is a mock of JwtauthVerify interface
type MockJwtauthVerify struct {
	ctrl     *gomock.Controller
	recorder *MockJwtauthVerifyMockRecorder
}

// MockJwtauthVerifyMockRecorder is the mock recorder for MockJwtauthVerify
type MockJwtauthVerifyMockRecorder struct {
	mock *MockJwtauthVerify
}

// NewMockJwtauthVerify creates a new mock instance
func NewMockJwtauthVerify(ctrl *gomock.Controller) *MockJwtauthVerify {
	mock := &MockJwtauthVerify{ctrl: ctrl}
	mock.recorder = &MockJwtauthVerifyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockJwtauthVerify) EXPECT() *MockJwtauthVerifyMockRecorder {
	return m.recorder
}

// Validate mocks base method
func (m *MockJwtauthVerify) Validate(ctx context.Context, token string) (*jwtauth.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, token)
	ret0, _ := ret[0].(*jwtauth.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate
func (mr *MockJwtauthVerifyMockRecorder) Validate(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockJwtauthVerify)(nil).Validate), ctx, token)
}
