// Code generated by MockGen. DO NOT EDIT.
// Source: ./verify_service.go

// Package mock_jwtauth is a generated GoMock package.
package mock_jwtauth

import (
	context "context"
	jwtauth "github.com/abyssparanoia/catharsis/pkg/jwtauth"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockVerifyService is a mock of VerifyService interface
type MockVerifyService struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyServiceMockRecorder
}

// MockVerifyServiceMockRecorder is the mock recorder for MockVerifyService
type MockVerifyServiceMockRecorder struct {
	mock *MockVerifyService
}

// NewMockVerifyService creates a new mock instance
func NewMockVerifyService(ctrl *gomock.Controller) *MockVerifyService {
	mock := &MockVerifyService{ctrl: ctrl}
	mock.recorder = &MockVerifyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockVerifyService) EXPECT() *MockVerifyServiceMockRecorder {
	return m.recorder
}

// Validate mocks base method
func (m *MockVerifyService) Validate(ctx context.Context, token string) (*jwtauth.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, token)
	ret0, _ := ret[0].(*jwtauth.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate
func (mr *MockVerifyServiceMockRecorder) Validate(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockVerifyService)(nil).Validate), ctx, token)
}
